user_info_1:
  bp: '4901'
  deviceName: 973QAEVEB8CS8
  port: '4701'
user_info_0:
  bp: '4900'
  deviceName: 681c4234
  port: '4700'
user_info_0:
  bp: '4900'
  deviceName: 681c4234
  port: '4700'
user_info_1:
  bp: '4901'
  deviceName: 973QAEVEB8CS8
  port: '4701'
